name: Node CI

on: [push]

jobs:
  build:
    name: intento de compilacion
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: MongoDB in GitHub Actions
        uses: superchargejs/mongodb-github-action@1.1.0
        with:
          mongodb-version: v4.2.2
      - name: ir al directorioo
        run: ls
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
         npm ci
         npm run build --if-present
         npm run dev
        env:
          CI: true
