name: Node CI

on: [push]

jobs:
  build:
    name: intento de compilacion
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: ir al directorioo
        uses: ls
